import React, { useState } from 'react'
import { motion } from 'framer-motion'
import { Search, Upload, FileText, Download, Sparkles } from 'lucide-react'

const PolicySearch = () => {
  const [searchQuery, setSearchQuery] = useState('')
  const [uploadedFile, setUploadedFile] = useState<File | null>(null)
  const [summary, setSummary] = useState('')
  const [isProcessing, setIsProcessing] = useState(false)

  const mockPolicies = [
    {
      id: 1,
      title: 'Green Building Standards 2024',
      category: 'Environment',
      summary: 'New regulations for sustainable construction practices and energy efficiency requirements.',
      relevance: 95,
      lastUpdated: '2024-01-15'
    },
    {
      id: 2,
      title: 'Urban Transportation Policy',
      category: 'Transport',
      summary: 'Guidelines for public transit expansion and electric vehicle infrastructure.',
      relevance: 87,
      lastUpdated: '2024-01-10'
    },
    {
      id: 3,
      title: 'Waste Management Framework',
      category: 'Environment',
      summary: 'Comprehensive approach to waste reduction, recycling, and circular economy principles.',
      relevance: 82,
      lastUpdated: '2024-01-08'
    }
  ]

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (file) {
      setUploadedFile(file)
    }
  }

  const handleSummarize = async () => {
    if (!uploadedFile) return
    
    setIsProcessing(true)
    // Simulate AI processing
    setTimeout(() => {
      setSummary(`
        **Policy Summary Generated by IBM Granite LLM**
        
        **Document:** ${uploadedFile.name}
        
        **Key Points:**
        • This policy establishes new sustainability standards for urban development
        • Mandatory green building certifications for all new constructions over 5,000 sq ft
        • 30% reduction in carbon emissions required by 2030
        • Incentives for renewable energy adoption in residential and commercial sectors
        • Enhanced public transportation infrastructure with electric bus fleet expansion
        
        **Impact Assessment:**
        • Estimated 25% reduction in city-wide energy consumption
        • Creation of 2,500 green jobs over the next 5 years
        • $50M investment in renewable energy infrastructure
        
        **Implementation Timeline:**
        • Phase 1: Q2 2024 - Policy framework establishment
        • Phase 2: Q4 2024 - Pilot program launch
        • Phase 3: Q2 2025 - Full implementation
        
        **Citizen Benefits:**
        • Lower utility costs through energy efficiency
        • Improved air quality and public health
        • Enhanced property values in green-certified buildings
      `)
      setIsProcessing(false)
    }, 3000)
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="card"
      >
        <div className="flex items-center space-x-3 mb-4">
          <div className="p-2 bg-blue-100 rounded-lg">
            <FileText className="w-6 h-6 text-blue-600" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Policy Search & Summarization</h1>
            <p className="text-gray-600">Search existing policies or upload documents for AI-powered summarization</p>
          </div>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Search Section */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.1 }}
          className="card"
        >
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Search Policies</h2>
          
          <div className="relative mb-6">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
            <input
              type="text"
              placeholder="Search policies by keyword, category, or topic..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="input-field pl-10"
            />
          </div>

          <div className="space-y-4">
            {mockPolicies.map((policy) => (
              <div key={policy.id} className="border border-gray-200 rounded-lg p-4 hover:border-blue-300 transition-colors">
                <div className="flex items-start justify-between mb-2">
                  <h3 className="font-medium text-gray-900">{policy.title}</h3>
                  <span className="text-xs bg-blue-100 text-blue-800 px-2 py-1 rounded-full">
                    {policy.relevance}% match
                  </span>
                </div>
                <p className="text-sm text-gray-600 mb-2">{policy.summary}</p>
                <div className="flex items-center justify-between text-xs text-gray-500">
                  <span className="bg-gray-100 px-2 py-1 rounded">{policy.category}</span>
                  <span>Updated: {policy.lastUpdated}</span>
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Upload & Summarize Section */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
          className="card"
        >
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Document Summarization</h2>
          
          <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center mb-4">
            <Upload className="w-8 h-8 text-gray-400 mx-auto mb-2" />
            <p className="text-sm text-gray-600 mb-2">Upload a policy document for AI summarization</p>
            <input
              type="file"
              accept=".pdf,.doc,.docx,.txt"
              onChange={handleFileUpload}
              className="hidden"
              id="file-upload"
            />
            <label htmlFor="file-upload" className="btn-primary cursor-pointer inline-block">
              Choose File
            </label>
          </div>

          {uploadedFile && (
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <FileText className="w-4 h-4 text-blue-600" />
                  <span className="text-sm font-medium text-blue-900">{uploadedFile.name}</span>
                </div>
                <button
                  onClick={handleSummarize}
                  disabled={isProcessing}
                  className="btn-primary flex items-center space-x-2 text-sm"
                >
                  <Sparkles className="w-4 h-4" />
                  <span>{isProcessing ? 'Processing...' : 'Summarize'}</span>
                </button>
              </div>
            </div>
          )}

          {summary && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-green-50 border border-green-200 rounded-lg p-4"
            >
              <div className="flex items-center justify-between mb-3">
                <h3 className="font-medium text-green-900">AI Summary Generated</h3>
                <button className="text-green-600 hover:text-green-800">
                  <Download className="w-4 h-4" />
                </button>
              </div>
              <div className="text-sm text-green-800 whitespace-pre-line">
                {summary}
              </div>
            </motion.div>
          )}

          {isProcessing && (
            <div className="flex items-center justify-center py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
              <span className="ml-3 text-sm text-gray-600">IBM Granite LLM is analyzing your document...</span>
            </div>
          )}
        </motion.div>
      </div>
    </div>
  )
}

export default PolicySearch